### ISSUE TITLE
Getting errors after following instructions

### ISSUE THREAD

**Issue by melalj** [balupton/dotfiles#2]
After following your instructions I got this list of errors, and cannot run an bash commands:

<img width="350" alt="screen shot 2017-09-18 at 2 44 41 pm" src="https://user-images.githubusercontent.com/3869766/30566227-0f48067e-9c80-11e7-9a99-621314c37829.png">

**Comment by balupton** [comment]
Strange. I’ll need to remote in. And figure out what is going on. Pick a time on https://balupton.com/meet

For the meantime, removing the parts that were inserted into your bashrc or bash_profile will skip loading the dotfiles, as all the dotfiles are in the .scripts directory

**Comment by balupton** [comment]
fixed with https://github.com/balupton/dotfiles/commit/57763dff3e004408ecb6cecbc3b58c7dc763e785
